name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ Checkout code
      uses: actions/checkout@v3

    - name: ðŸ” Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: ðŸ³ Build & Push Node
      run: |
        docker build -t mourphy/node-service:v2 ./microservices/node-service
        docker push mourphy/node-service:v2

    - name: ðŸ³ Build & Push Python
      run: |
        docker build -t mourphy/python-service:v2./microservices/python-service
        docker push murphy/python-service:v2

    - name: ðŸ³ Build & Push Go
      run: |
        docker build -t mourphy/go-service:v2 ./microservices/go-service
        docker push mourphy/go-service:v2

    - name: âš™ï¸ Setup kubectl & Helm
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: ðŸš€ Deploy with Helm
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        helm upgrade --install microapp ./helm/microapp --atomic --timeout 2m
